### ISSUE TITLE
Why isn't CLU available in the Raku ecosystem?

### ISSUE THREAD

**Issue by lizmat** [corporate-runaways/TooLoo#4]
Why isn't CLU available in the Raku ecosystem?

Being able to say:
````
zef install CLU
````
would be much better, no?

**Comment by masukomi** [comment]
I didn't want to .... pollute the pool as it were with something i figured essentially no-one else would care about. Still trying to figure out what's appropriate / not to put up there. 

HOWEVER. Given your prominence and experience with Raku stuff @lizmat, I'll take this as a hint that I should upload it. ;) 

Thank you.

will close this ticket as soon as I do.

**Comment by masukomi** [comment]
is there. I screwed up and didn't have the url pointing back to this repo in the meta6, but i'll fix that with the next version bump. ;)

**Comment by lizmat** [comment]
That's what I like about App::Mi6: it's one of the things it takes care of :-)
